SINGULARITY?=apptainer
DEF=el9.def
SBX=el9.sbx
SIF=el9.sif

.PHONY : all
all : ${SBX} ${SIF}

.PHONY : clean
clean :
	if [ -d ${SBX} ] ; then \
	    ${SINGULARITY} exec --pwd /opt --fakeroot --writable ${SBX} sh -c \
	        "rm -rf /usr/share/polkit-1/rules.d /etc/polkit-1/rules.d"; \
	fi
	rm -rf ${SBX} ${SIF} build-temp-* *~

${SBX} : ${SIF}
	${SINGULARITY} build --fakeroot --fix-perms --sandbox ${SBX} ${SIF}

${SIF} : ${DEF}
	${SINGULARITY} build --fakeroot --fix-perms ${SIF} ${DEF}

.PHONY : shell
shell : ${SBX}
	${SINGULARITY} shell --pwd /opt --fakeroot --writable ${SBX}
