#!/usr/bin/env nextflow
nextflow.enable.dsl=2

// 1. 全体デフォルト値の定義（未定義時のフォールバック）
params.memory = 32
params.threads = 8

// パラメータの初期化
params.qiime2_dada2_trim_left_f = 0
params.qiime2_dada2_trim_left_r = 0
params.qiime2_dada2_trunc_len_f = 230
params.qiime2_trunc_len_r = 230

params.qiime2_gg2_16s_target_region = 'v4'
params.qiime2_gg2_rrndb_mode = 'right' // rrnDBコピー数探索モードのデフォルト

// 機能アノテーション関連パラメータのデフォルト追加
if (!params.containsKey('annotation_table')) {
    params.annotation_table = "${params.petagenomeDir}/data/greengenes2/genome_annotations_table.tsv"
}
params.functional_annotations = "KO,MetaCyc"

params.qiime2_gg2_16s_backbone_fna = "${params.petagenomeDir}/data/greengenes2/2024.09.backbone.full-length.fna.qza"
params.qiime2_gg2_16s_taxonomy = "${params.petagenomeDir}/data/greengenes2/2024.09.backbone.tax.qza"
params.qiime2_gg2_16s_rrndb_stats = "${params.petagenomeDir}/data/rrnDB/rrnDB-5.10_pantaxa_stats_RDP.tsv.gz"

// 必須パラメータのチェック
if (!params.containsKey('petagenomeDir') || !params.petagenomeDir) {
    error "Error: 'petagenomeDir' parameter is not specified. Please provide it."
}

include { createNullParamsChannel; getParam; clusterOptions; processProfile; createPairsChannel; createSeqsChannel } \
    from "${params.petagenomeDir}/nf/common/utils"

// 下位モジュール（lv1）のインポート
include { QIIME2_DADA2_SUB } from "${params.petagenomeDir}/nf/lv1/qiime2_dada2"
include { QIIME2_GREENGENES2_16S_SUB } from "${params.petagenomeDir}/nf/lv1/qiime2_gg2_16s"

// ==========================================
// 追加：FASTA直接入力からDADA2出力を模倣するプロセス（標準ライブラリのみ使用）
// ==========================================
process qiime2_import_fasta_as_features {
    tag "${sample_id}"
    container = "${params.petagenomeDir}/modules/qiime2/qiime2.sif"
    publishDir "${params.output}/qiime2_dada2/${sample_id}", mode: 'symlink', enabled: params.publish_output

    input:
        tuple val(sample_id), path(fasta_file)

    output:
        tuple val(sample_id), 
              path("${sample_id}/table.qza"), 
              path("${sample_id}/rep-seqs.qza"), 
              path("${sample_id}/denoising-stats.qza"), 
              path("${sample_id}/base-transition-stats.qza")

    script:
        """
        export PYTHONWARNINGS="ignore"
        export XDG_CONFIG_HOME=/tmp/qiime2_config
        export MPLCONFIGDIR=/tmp/matplotlib_config

        mkdir -p ${sample_id}

        # 1. 代表配列 (rep-seqs.qza) のインポート
        qiime tools import \
            --type 'FeatureData[Sequence]' \
            --input-path ${fasta_file} \
            --output-path ${sample_id}/rep-seqs.qza

        # 2. 標準PythonだけでFASTAをパースしてBIOMテーブルを生成
        python3 - <<EOF
import biom
import pandas as pd

fasta_path = "${fasta_file}"
record_ids = []

# Biopythonを使わず標準機能でFASTAのヘッダー（ID）を抽出
with open(fasta_path, 'r') as f:
    for line in f:
        if line.startswith('>'):
            # スペース等があれば最初の単語をIDとする
            rec_id = line[1:].strip().split()[0]
            record_ids.append(rec_id)

# すべての配列IDに対してカウント1のダミーテーブルを作成
data = pd.DataFrame(1, index=record_ids, columns=["${sample_id}"])
table = biom.Table(data.values, data.index, data.columns)

biom_file = "${sample_id}/feature_table.biom"
with open(biom_file, "w") as f:
    table.to_json("Generated by pipeline fasta bypass", f)
EOF

        # 3. フィーチャーテーブル (table.qza) のインポート
        qiime tools import \
            --type 'FeatureTable[Frequency]' \
            --input-path ${sample_id}/feature_table.biom \
            --input-format BIOMV100Format \
            --output-path ${sample_id}/table.qza

        # 4. 後続プロセスが必要とするダミーの統計ファイルを作成
        touch ${sample_id}/denoising-stats.qza
        touch ${sample_id}/base-transition-stats.qza
        """
}

// ==========================================
// サブワークフロー（処理の本体）
// ==========================================
workflow QIIME2_16S_PIPELINE_SUB {
    take:
    p
    reads
    target_region
    backbone_fna
    taxonomy
    rrndb_stats
    rrndb_mode
    annotation_table
    target_annots
    is_fasta

    main:
    // FASTAの場合はDADA2をスキップし、それ以外は従来のDADA2をそのまま実行
    if (is_fasta) {
        dada2_out = qiime2_import_fasta_as_features(reads)
    } else {
        dada2_out = QIIME2_DADA2_SUB(p, reads)
    }

    // B. Greengenes2 (16S用) による系統配置・タクソノミ付与 & 機能アノテーション集計
    gg2_out = QIIME2_GREENGENES2_16S_SUB(
        p,
        dada2_out,
        target_region,
        backbone_fna,
        taxonomy,
        rrndb_stats,
        rrndb_mode,
        annotation_table,
        target_annots
    )

    emit:
    gg2_out = gg2_out
}

// ==========================================
// コマンドライン用エントリーポイント (-entry)
// ==========================================
workflow QIIME2_16S_PIPELINE_ALL {
    p = createNullParamsChannel()

    // 入力ファイルがFASTA形式かどうかを安全に判定
    def is_fasta = false
    if (params.containsKey('qiime2_reads')) {
        def r_str = params.qiime2_reads.toString().toLowerCase()
        if (r_str.endsWith('.fasta') || r_str.endsWith('.fa') || r_str.endsWith('.fna')) {
            is_fasta = true
        }
    }

    // FASTAのときは単一配列チャンネル、それ以外は元のペアエンドチャンネルを生成
    def reads
    if (is_fasta) {
        reads = createSeqsChannel(params.qiime2_reads)
    } else {
        reads = createPairsChannel(params.qiime2_reads)
    }

    region_ch = Channel.value(params.qiime2_gg2_16s_target_region)
    mode_ch = Channel.value(params.qiime2_gg2_rrndb_mode)
    
    // 機能アノテーション関連チャンネルの作成
    annotation_ch = Channel.value(file(params.annotation_table, checkIfExists: true))
    annots_ch = Channel.value(params.functional_annotations)

    // Nextflowの標準機能（checkIfExists: true）で安全にファイル存在チェックを行う
    backbone_ch = Channel.value(file(params.qiime2_gg2_16s_backbone_fna, checkIfExists: true))
    taxonomy_ch = Channel.value(file(params.qiime2_gg2_16s_taxonomy, checkIfExists: true))
    rrndb_ch = Channel.value(file(params.qiime2_gg2_16s_rrndb_stats, checkIfExists: true))

    out_ch = QIIME2_16S_PIPELINE_SUB(
        p,
        reads,
        region_ch,
        backbone_ch,
        taxonomy_ch,
        rrndb_ch,
        mode_ch,
        annotation_ch,
        annots_ch,
        is_fasta
    )

    out_ch.gg2_out.view { i -> "QIIME2 16S PIPELINE OUT: $i" }
}

workflow {
    QIIME2_16S_PIPELINE_ALL()
}