MOD=virsorter

BUILD_DEP_DIRS=../common

include ../common/common.mk

.PHONY : help
help : ${SIF}
	${SINGULARITY} exec --no-home \
                        --pwd /opt \
                        ${SIF} \
                        wrapper_phage_contigs_sorter_iPlant.pl --help

.PHONY : version
version : ${SIF}
	${SINGULARITY} exec --no-home \
                        --pwd /opt \
                        ${SIF} \
                        wrapper_phage_contigs_sorter_iPlant.pl --help | head -n 5
